[package]
name = "vex-libunwind-sys"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "FFI bindings to LLVM libunwind for VEX V5 robots"
keywords = ["vex", "v5", "unwind", "libunwind"]
categories = [
    "external-ffi-bindings",
    "embedded",
    "science::robotics",
    "no-std::no-alloc",
]
authors = [
    "vexide",
    "doinkythederp <doinkythederp@icloud.com>",
    "Tropical",
    "Gavin Niederman <gavinniederman@gmail.com>",
]
repository = "https://github.com/vexide/vex-libunwind"
homepage = "https://vexide.dev"

[dependencies]

[lints]
workspace = true
